version: '3.9'

x-common-variables:
  &common-variables
  MYSQL_DATABASE: nitc_pms
  MYSQL_USER: akhilsarwarth
  MYSQL_PASSWORD: Qwertyuiop[]*123#

services:
  mysql_db:
    image: mysql
    restart: always
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password"
      ]
    cap_add:
      - SYS_NICE
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: Qwertyuiop[]*123#
      MYSQL_HOST: localhost
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mysql_db",
          "-uakhilsarwarth",
          "-pQwertyuiop[]*123#"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
